// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BCheckbox: typeof import('./src/components/bElForm/items/bCheckbox.vue')['default']
    BDatePicker: typeof import('./src/components/bElForm/items/bDatePicker.vue')['default']
    BElForm: typeof import('./src/components/bElForm/index.vue')['default']
    BElFormItem: typeof import('./src/components/bElForm/items/bElFormItem.vue')['default']
    BInput: typeof import('./src/components/bElForm/items/bInput.vue')['default']
    BRadio: typeof import('./src/components/bElForm/items/bRadio.vue')['default']
    BSelect: typeof import('./src/components/bElForm/items/bSelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FileUpload: typeof import('./src/components/uploads/fileUpload.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    ImageUpload: typeof import('./src/components/uploads/imageUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
